[package]
name = "game"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
geomath.workspace = true
serpent.workspace = true
sdl2.workspace = true
rand.workspace = true