[workspace]
resolver = "3"
members = [
    "snake"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["CieriA"]
license = "MIT"
repository = ""
readme = "README.md"


[workspace.dependencies]

